TPC-Council/HammerDB

src/postgresql/pgoltp.tcl

#92 rewrote two of the stored procedure implementations in `pgoltp.tcl` for higher performance. In the neword procedure, [one of the update queries](https://github.com/TPC-Council/HammerDB/pull/92/files#diff-d897f78b12b2f4c500c61976159deb04R547) now joins the stock table with the unnest function on the s_w_id column. While the PostgreSQL planner is able to use the primary key index during a join, it is not able to prune away partitions when the `stock` table is partitioned based on the join. Hence, the neword procedure now always updates all partitions of the stock table even if it is partitioned on s_w_id and there is only a single value of s_w_id.
We observed a significant drop in performance when running the new stored procedure implementation against a PostgreSQL cluster that uses the …

Add partitioning hints in PostgreSQL neword transaction

---

src/generic/genvu.tcl

Fix temp environment variables not detected

---

src/postgresql/pgoltp.tcl

Fix for bug described in Issue #134

update dbms_random for PostgreSQL neword infinite loop

---

src/generic/gencli.tcl

Fix distributescript applyctexthighlight error

---

src/generic/gencli.tcl

Fix for Issue #176 adding bgerror function to CLI

Add bgerror to CLI

---

src/generic/gencli.tcl

Change runtimer from synchronous (with update every second) to asynchronous as per #179

Update CLI runtimer to asynchronous

---

src/generic/gencli.tcl

Added a return statement after writing out usage message for customscript.

Proposed fix to Issue #184

---

config/steps.xml
hammerdbcli
src/generic/gencli.tcl
src/generic/genstep.tcl

Adds feature enable Variable Load/Stress Testing enhancement workload 

---

src/mysql/mysqloltp.tcl

Fix for Issue #216 by reordering prepared statements

Fix for Issue #216 Unkown prepared statement handler with connect pool

---

config/generic.xml
hammerdb
hammerdbcli
src/db2/db2opt.tcl
src/generic/gencli.tcl
src/generic/gentc.tcl
src/generic/gentccli.tcl
src/generic/gentccmn.tcl
src/mssqlserver/mssqlsopt.tcl
src/mysql/mysqlopt.tcl
src/oracle/oraopt.tcl
src/postgresql/pgopt.tcl

Add transaction counter to CLI and transaction counter logging to both CLI and GUI

Add TX Counter to CLI and TX Counter logging

---

ChangeLog
agent/agent
agent/mpstat.bat
hammerdb
hammerdbcli
hammerdbws
src/generic/gened.tcl

Update versions, changelog and dates for v4.1

---

config/oracle.xml
src/generic/genstep.tcl
src/oracle/oraopt.tcl

fix error in steprun command for oracle with introduced mismatch from timeprofile variable

Update ora_timeprofile variable for runstep compatibility

---

ChangeLog
agent/agent
hammerdb
hammerdbcli
hammerdbws

Updates version number and changelog for v4.2

Update versions and changelog for v4.2

---

src/mssqlserver/mssqlsoltp.tcl

Changes/Updates to SQL Server Schema/Stored procedures as per Issue #371

SQL Server Schema/Stored Procedure Updates

---

Docker/Dockerfile
Docker/Readme

Updated HammerDB version to 4.5

Hdb docker

---

src/generic/gentccmn.tcl
src/mariadb/mariaotc.tcl
src/mysql/mysqlotc.tcl

Corrects issues with MySQL/MariaDB transaction counter when cannot connect, closes #418

Fix MySQL/MariaDB TX Count Error Handling on Connection

---

config/generic.xml
hammerdbcli
src/generic/gencli.tcl
src/generic/gened.tcl
src/generic/genhelp.tcl
src/generic/geninit.tcl
src/generic/gentab.tcl
src/generic/gentheme.tcl
src/generic/genvu.tcl

Pull Request adds queryable repository storage for job information, ported from web service to CLI & GUI

Job Storage for Issue #420

---

Build/Bawt-2.1.0/Setup/HammerDB-Linux.bawt
Build/Bawt-2.1.0/Setup/HammerDB-Windows.bawt

adds tkpath package to source build for advanced SVG canvas support https://tclbitprint.sourceforge.net/

Add tkpath to build

---

src/db2/db2olap.tcl
src/db2/db2oltp.tcl

Use db2tcl to create and drop database for DB2.

Use db2tcl to create and drop database for DB2

---

DocBook/docs.xml

Fix for issue #534 doc advises VU count can't be lower than warehouse count when it should say higher.

Fix doc bug for VU/warehouse count

---

src/db2/db2olap.tcl
src/db2/db2oltp.tcl

Resolves https://github.com/TPC-Council/HammerDB/issues/548 by allowing a database to pre-created for the TPROC-C & TPROC-H. Workload will check to verify that if the database exists it is empty before using it for the build.
If a database does not exist it will continue to use the modified behaviour by creating one.

Allow using existing empty database for Db2 TPROC-C and TPROC-H

---

src/generic/genhelp.tcl

Adds back help message removed in error by commit 3de91e5

Fix commit 3de91e5 removed getchart help message

---

src/generic/gened.tcl

Modify Webservice to Web Service in GUI field for consistency with other entries

Fix typo in Web Service port label

---

ChangeLog

Update changelog with addtional pull requests for bug fixes

Update v4.8 changelog with bug fixes

---

Docker/mssqls/Dockerfile

Link to Issue:
https://github.com/TPC-Council/HammerDB/issues/595
Built and tested successfully with Docker v24.0.5

Edited Dockerfile to install a specific version of msodbcsql18

---

ChangeLog
agent/agent
hammerdb
hammerdbcli
hammerdbws

Update version numbers and changelog to v4.9

4.9 version numbers and changelog

---

ChangeLog

Update the ChangeLog for additional BCP pull request

Update ChangeLog for PR 614

---

ChangeLog

Update ChangeLog for PR 616

---

modules/comm-4.5.6.tm

Replace error with warning if remote application connects to comm port

---

config/mssqlserver.xml
src/mssqlserver/mssqlsolap.tcl
src/mssqlserver/mssqlsopt.tcl

Create an option for users loading TPCH for MSSQL to perform a more advanced statistical analysis. Option is set to false by default because of the large increase to load time.

MSSQL TPCH Create Advanced Statistics

---

ChangeLog
agent/agent
hammerdb
hammerdbcli
hammerdbws
src/generic/gened.tcl

Increase version numbers and Changelog for v4.10 release

v4.10 Version numbers and Changelog

---

Docker/base/Dockerfile

Apologies, there was a typo in the previous commit.

version bump to 4.10

---

modules/jobs-1.0.tm

Change value for SQLite jobs database size from KB to bytes

Fix incorrect value for SQLite database

---

config/generic.xml
modules/jobs-1.0.tm
src/generic/gencli.tcl
src/generic/gened.tcl
src/generic/genhelp.tcl
src/generic/genmetricscli.tcl

Adds features discussed in #661. 
Creates ability to specify a performance profile id to group TPROC-C jobs and produces a graph to show the summary performance of all jobs.

Adds Performance Profile for TPROC-C Jobs

---

ChangeLog
agent/agent
hammerdb
hammerdbcli
hammerdbws

Add Changelog and version numbers for v4.11

v4.11 Version numbers and Changelog

---

ChangeLog

For consistency, update Changelog for Pull Request #709

Update Changelog for PR #709

---

src/generic/gencli.tcl
src/postgresql/pgoltp.tcl

Closes issue #720 as a result of errors from inline editing of TPROC-C options for PostgreSQL

Fix issues with PostgreSQL inline edit

---

modules/jobs-1.0.tm

As discussed in #735 modifications to web service homepage and adds a job summary link to display a header and all available charts in one location. Aim to is to provide access to insights quicker.

Add results to web service homepage

---

ChangeLog
agent/agent
hammerdb
hammerdbcli
hammerdbws

Version number and changelog updates

Update version numbers and changelog for v4.12

---

Docker/base/Dockerfile

Increase docker version to v4.12

Docker version bump to 4.12

---

src/generic/gencli.tcl

Adds the keepalive to the datagenrun command so it can be run within a scripted environment.

Add keepalive to datagenrun

---

src/postgresql/pgoltp.tcl

CreateUserDatabase returns error in case the user does not have the ALTER DATABASE permissions. It apears that ALTER DATABASE command is not even necessary if the user is already the database owner. So it should be possible to skip this command.

ALTER DATABASE only if necessary
