- src/postgresql/pgoltp.tcl
The $pg_dbase argument is in the wrong place causing errors when running against PostgreSQL (the password is used as the username).
> Fix order of arguments to do_tpcc in pgoltp.tcl

- src/generic/genws.tcl
Fixes Issue #61 to include current value to show the currently set database.
```
{
"current": "Oracle",
"ora": "Oracle",
"mssqls": "MSSQLServer",
"db2": "Db2",
"mysql": "MySQL",
"pg": "PostgreSQL",
"redis": "Redis"
}
```
> Fixed WebService API does not return current db

- hammerdbcli
- src/generic/gencli.tcl
- src/generic/genmodes.tcl
These updates add the the Master Slave Modes feature to the CLI (https://www.hammerdb.com/docs/ch12.html.)  Setting an instance of HammerDB as a Master enables connecting other instances as Slaves that are then driven by the commands from the Master. Feature is typically used for testing virtualization and clustering.
> Added Master/Slave Modes to CLI

- config/postgresql.xml
- src/postgresql/pgolap.tcl
- src/postgresql/pgoltp.tcl
- src/postgresql/pgopt.tcl
Add prepared statement functionality for PostgreSQL as per Issue #94
> PostgreSQL prepared statements for functions and tablespace option for schema builds

- src/generic/gentpcc.tcl
- src/oracle/oraoltp.tcl
- src/postgresql/pgoltp.tcl
Rewrite of the functions and stored procedures using bulk processing and more RETURNING functionality.  The approach taken is based on that the in Oracle TPC-C Full Disclosure report: http://c970058.r58.cf2.rackcdn.com/fdr/tpcc/Cisco-Oracle%20C240%20TPC-C%20FDR.pdf
On a CPU bound system, testing reveals increase in NOPM:
PG10: 51753 to 69200 (34%)
PG11: 62131 to 74166 (19%)
Whilst every effort has been made to verify no regression in performance, the lack of full regression pack makes it hard to be certain but the workload appears to be equivalent.
Note that one issue was "fixed" i.e. non local order distribution.  I don't believe this has any impact of workload but does adhere to the TPC-C specification.
> Refactor Postgres procedural code for performance

- src/db2/db2oltp.tcl
- src/mssqlserver/mssqlsoltp.tcl
- src/mysql/mysqloltp.tcl
- src/oracle/oraoltp.tcl
- src/postgresql/pgoltp.tcl
- src/redis/redisoltp.tcl
- src/trafodion/trafoltp.tcl
Detailed in Issue #99 - reports test results as NOPM from TPM
> Reverse print out of metrics to put NOPM ahead of TPM

- config/database.xml
Detailed in issue #100 commented out Redis so it doesn't show in the default database list due to single threaded performance bottleneck. User can still uncomment to use unsupported. Will not develop further features such as graphical statistics for unsupported workloads.
> Deprecated Redis

- src/postgresql/pgopt.tcl
#98 accidentally reverted the tablespace changes to `pgopt.tcl` made by #95, which causes TPC-C on PostgreSQL to fail with `Error: can't read "pg_tspace": no such variable`
This PR redoes the changes from #95 to fix the issue. There were some [minor changes to pgopt.tcl](https://github.com/TPC-Council/HammerDB/pull/98/files#diff-ddb170835ad5c6cdafd7722c4e0623b1R340) in #98 related to handling of `pg_async_scale`. I left those unchanged.
> Redo PostgreSQL tablespace changes from #95 in pgopt.tcl

- src/generic/gencli.tcl
Fix for Issue #118. Previous version mismatched odbc_driver as driver script variable and also omitted multiple values separated by spaces. This version fixes both issues in the CLI and tested with new feature of Master/Slave in the CLI to ensure values with spaces are correctly translated to the remote instance of HammerDB.
> Fix for Issue #118 using diset with variables with spaces

- src/postgresql/pgolap.tcl
- src/postgresql/pgoltp.tcl
Adds support for using existing user and database in Postgres.
Instead of the current behavior of always creating user and database, this checks if the user or database exists and uses them if they do. The database is only used when there are no tables in it. If there are tables, an error is given.
This PR is opened for the changes discussed in #122.
> Use Existing User and DB in Postgres

- config/database.xml
HammerDB v4.0 moves to TCL 8.6.10. At 8.6.10 the tdbc::odbc library name moves from 1.1.0 to 1.1.1.  The code for tdbc::odbc in HammerDB v3.3 was already at the version as it had been modified to resolve the typo of #if defined (__WIN64) by removing additional underscore that caused SQULEN issues and added the essential evaldirect command.  It has been verified that the code is the same as 8.6.10 is based on. This change updates to the correct library name.
> Update SQL Server library version number for TCL8.6.10

- ChangeLog
- config/mssqlserver.xml
Bring SQL Server ODBC Driver for Windows to version ODBC Driver 17 for SQL Server. Tested on SQL Server 2019.
> Update SQL Server ODBC Driver

- src/mssqlserver/mssqlsolap.tcl
- src/mssqlserver/mssqlsoltp.tcl
For sql server on aws-rds, sp_updatestats fails due to permission error. Here is an article discussing this issue. https://yatb.mitza.net/2017/03/running-spupdatestats-on-aws-rds.html
The error message looks like this when I run tpch or tpcc on aws-rds
```
Vuser 1:UPDATING SCHEMA STATISTICS
Error in Virtual User 1: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]User does not have permission to perform this action.
(executing the statement)
Vuser 1:FINISHED FAILED
ALL VIRTUAL USERS COMPLETE
```
The work around is to create a stored procedure which wraps sp_updatestats and run it under a different user.
> Fixed statistics updates failure on AWS

- modules/task-1.1.1.tm
Add task manager module for better command line timing based on coroutines. This module enables the creation of step/variable workloads as described in #103 and allows out to the main thread during driver script runs improving on runtimer.
> Add task manager module

- src/postgresql/pgoltp.tcl
Fix for Issue #194 where datatype change caused a performance regression when the stored procedure option is selected. Update has been tested and performance restored changing numeric to integer for the payment stored procedure. Other stored procedures also checked and no further similar issues found.
> Fix for Issue #194 Postgres datatype change from number to integer

- config/generic.xml
- config/oracle.xml
- modules/xtprof-1.0.tm
- src/generic/gencli.tcl
- src/generic/gened.tcl
- src/generic/gentccmn.tcl
- src/generic/gentpcc.tcl
- src/generic/genws.tcl
- src/oracle/oraoltp.tcl
- src/oracle/oraopt.tcl
Pull Request implements extended time profiling that captures timings for all Virtual Users and writes output to logfile.
> Extended Time Profiling as per Issue #224

- src/generic/gentccmn.tcl
Fix for Issue #242 when transaction counter start errors without logging enabled.
> Fix for Issue #242 can't read tc_flog no such variable

- config/generic.xml
- modules/xtprof-1.0.tm
Fix for Issue #247 where timing data times out when using a large number of virtual users with event driven scaling. Solution is to make timeout value user configurable and if timeout reached when no data reported to error but when some data reported to continue and calculate timings for those Virtual Users that did.
> Fix for Timing Data Times Out

- ChangeLog
- modules/xtprof-1.0.tm
Reinitialize xtprof thread shared variables on module load.
> Fix for Xtprof can retain old data

- config/connectpool/pgcpool.xml
- config/postgresql.xml
- src/postgresql/pgolap.tcl
- src/postgresql/pgoltp.tcl
- src/postgresql/pgopt.tcl
- src/postgresql/pgotc.tcl
Allow pg_sslmode argument to be passed into the postgres driver. Keep default argument value to prefer to make it compatible with default postgres value (refer to https://www.postgresql.org/docs/13/libpq-ssl.html)
pg_sslmode can be changed as follows:
hammerdb>dbset db pg
Database set to PostgreSQL
hammerdb>print dict
Dictionary Settings for PostgreSQL
connection {
pg_host    = localhost
pg_port    = 5432
pg_sslmode = prefer
}
...
hammerdb>diset connection pg_sslmode disable
Changed connection:pg_sslmode from prefer to disable for PostgreSQL
hammerdb>print dict
Dictionary Settings for PostgreSQL
connection {
pg_host    = localhost
pg_port    = 5432
pg_sslmode = disable
}
...
All new code of the whole pull request, including one or several files that are either new files or modified ones, …
> Add sslmode support for PostgreSQL database

- modules/tclreadline-1.2.tm
When running `./hammerdbcli auto somescript.ctl` on Linux it was
impossible to stop the benchmark by using Ctrl+C. This was pretty
annoying since it is the most common way to stop programs in a shell on
Linux. The reason was that the readline module was explicitly ignoring
SIGINT. This makes sense for interactive mode, but when using `auto`
there's no reason for this.
This change makes sure the signal capturing code is only executed once
`TclReadLine::interactive` is called.
> readline: only catch signals when using interact

- hammerdb
- hammerdbcli
- hammerdbws
If the $PATH variable contained spaces then it would result in an error
like this:
```
./hammerdb: 6: export: (x86)/Microsoft: bad variable name
```
By double quoting the usage of the existing $PATH variable bash handles
this correctly.
> Make Linux hammerdb executable work with spaces in PATH

- modules/tpcccommon-1.0.tm
- modules/tpchcommon-1.0.tm
When building the dataset I was able to max out the CPU on the
node that's running HammerDB (as opposed to the database that this node
is connecting to). Since generating data takes a significant amount of
time I took some time trying to find some low hanging fruit for
optimization.
After some profiling, by far the most CPU heavy function turned out to
be `MakeAlphaString`. After digging down even further it turns out that
the thing that makes this function slow is the amount of `rand` calls it
does. Since we cannot completely remove this `rand` call, I investigated
some ways of reducing the number of calls.
The new implementation is able to generate a sequence of 4 random
characters with a single `rand` call. This is done in two ways:
1. Pre-compute an array of all combinations of two …
> Optimize MakeAlphaString

- modules/tclreadline-1.2.tm
Fix for Issue #289, when run in Kubernetes interactive mode, getcols can return a terminal width of zero. This checks if the columns value is detected, if not it will set a default value of 80.
> Fix getcols can return zero, resulting in divide-by-zero

- modules/tclreadline-1.2.tm
Fix for  running ./hammerdbcli auto <tcl-file> in AWS Lambda function #320 
History files only dependent on HOME environment variable when running in interactive mode with prompt.
Using auto flag bypasses history preventing error in AWS lambda
> Move history file tracking to interactive

- config/connectpool/mariacpool.xml
- config/mariadb.xml
- src/mariadb/mariaolap.tcl
- src/mariadb/mariaoltp.tcl
- src/mariadb/mariaopt.tcl
- src/mariadb/mariaotc.tcl
Pull Request enables SSL network connectivity for MariaDB. .pem files should already be created and available in a readable directory and the MariaDB server enabled for SSL. 
Options allow one-way or two-way SSL to be selected. 
If SSL is successfully enabled the SSL cipher is reported. Where SSL is not enabled an empty string {} is reported. 
Where SSL filenames are given the names are concatenated to the CApath and passed directly for each individual file. If all filenames are empty then the CApath option will be passed instead with the directory name. 
The default SSL Cipher is listed as "server" meaning use the server default. This value can be changed to another available cipher. 
Note: the SSL Cipher requires an update to the mariatcl library and will only work from HammerDB v4.5 …
> Add SSL connection options to MariaDB

- src/mariadb/mariaoltp.tcl
Minor fix for bug introduced by modifying MariaDB connect procedure for SSL. By default autocommit is set to 0. Monitor VU needs value set to 1 otherwise querying of NOPM value returns 0. 
PR sets autocommit to 1 for the monitor VU to prestore previous behaviour.
> set MariaDB autocommit to 1 for Monitor VU

- src/postgresql/pgolap.tcl
- src/postgresql/pgoltp.tcl
Valid database names and usernames might have upper case characters. However, if
they are passed without proper escaping PostgreSQL will end up referencing the
name using wrong case and later the procedure will error on not finding the
correct username or database name.
Fix this by using double quotes when passing usernames or database names.
All new code of the whole pull request, including one or several files that are
either new files or modified ones, are contributed under the BSD-new license. I
am contributing on behalf of my employer Amazon Web Services, Inc.
> Escape username and database name in PostgreSQL procedures

- Docker/Dockerfile
- Docker/Readme
- Docker/odbc_cli/Readme
- Docker/sample_scripts/tprocc/db2_tprocc_build.tcl
- Docker/sample_scripts/tprocc/db2_tprocc_run.tcl
- Docker/sample_scripts/tprocc/maria_tprocc_build.tcl
- Docker/sample_scripts/tprocc/maria_tprocc_run.tcl
- Docker/sample_scripts/tprocc/mssqls_tprocc_build.tcl
- Docker/sample_scripts/tprocc/mssqls_tprocc_run.tcl
- Docker/sample_scripts/tprocc/mysql_tprocc_build.tcl
- Docker/sample_scripts/tprocc/mysql_tprocc_run.tcl
- Docker/sample_scripts/tprocc/ora_tprocc_build.tcl
- Docker/sample_scripts/tprocc/ora_tprocc_run.tcl
- Docker/sample_scripts/tprocc/pg_tprocc_build.tcl
- Docker/sample_scripts/tprocc/pg_tprocc_run.tcl
Dockerfile builds a ubuntu 20.04 HammerDB container that installs all the client libraries for databases supported by HammerDB. 
Adding some sample scripts for all databases to build schema and do a test run for TPROC-C workload.
> Added Dockerfile to build a HammerDB container and TPROC_C sample scripts to build schema and run tests

- src/mysql/mysqloltp.tcl
Fix for Issue #365 - Error not reported correctly as RAISEERROR variable not found.
Remove RAISEERROR variable for Asynch clients.
> Fix RAISEEROR error in Asynch connect

- src/db2/db2oltp.tcl
- src/mariadb/mariaoltp.tcl
- src/mysql/mysqloltp.tcl
Testing shows on MariaDB, MySQL and Db2 shows o_all_local updated correctly. 
No major impact on performance discovered on local PC testing.
```
MariaDB [(none)]> use tpcc;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A
AFTER INSTALL
Database changed
MariaDB [tpcc]> select count(*) from orders where o_all_local = 0;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.101 sec)
MariaDB [tpcc]> select count(*) from orders where o_all_local = 1;
+----------+
| count(*) |
+----------+
|   600000 |
+----------+
1 row in set (0.113 sec)
ORIG
MariaDB [tpcc1]> select count(*) from orders where o_all_local = 0;
+----------+
| count(*) |
+----------+
|    44876 |
+----------+
1 row in set …
```
> Fix for o_all_local value update and insert

- src/mssqlserver/mssqlsoltp.tcl
Corrects bug where no_ol_i_id is incorrectly set to a random number from 1,000,000 when it should be 100,000.
Have checked all other database implementations and all are correct apart from this.
> MSSQLS SET no_ol_i_id to correct value

- src/postgresql/pgmet.tcl
- src/postgresql/pgolap.tcl
- src/postgresql/pgoltp.tcl
- src/postgresql/pgotc.tcl
Fix for issue #400 by removing previous workaround that did a double connection on Windows.
Fix has been tested on both Linux and Windows with TPROC-C & TPROC-H workloads.
> Remove reconnect for PostgreSQL on windows

- src/mariadb/mariaopt.tcl
This patch adds the ability to pass empty string as the path to certificate authority (CA), when using SSL connection to MariaDB.
Currently when trying to authenticate MariaDB user using SSL key and SSL certificate, HammerDB also requires providing path CA. Providing CA is a recommended solution in production environment, but it is not required. Especially when using self-signed certificates, such a CA cannot be properly verified by OpenSSL and thus it can be rejected, so we want to avoid such a scenario by not specifying path to CA.
Signed-off-by: Igor Konopko <igor.j.konopko@intel.com>
> HammerDB: Allow to skip CA for MariaDB

- config/db2.xml
- config/mariadb.xml
- config/mssqlserver.xml
- config/mysql.xml
- config/oracle.xml
- config/postgresql.xml
- config/redis.xml
- config/trafodion.xml
- hammerdbws
- modules/tclreadline-1.2.tm
- src/generic/gencli.tcl
- src/generic/genhelp.tcl
- src/generic/gentcws.tcl
- src/generic/genws.tcl
Pull request addresses issues #387 #403 and fixes #414 allowing a simpler command line script such as the following to run a basic timed workload automating loadscript, vucreate and runtimer.
```
dbset db maria
dbset bm TPROC-C
diset tpcc maria_driver timed
diset tpcc maria_rampup 1
diset tpcc maria_duration 2
vuset vu vcpu
vurun
```
The PR automates loadscript for the CLI as per #403 however only if there is no script loaded at all. The script could be refreshed for each run when vucreate is run however if customscript has been used then it would always be overwritten, therefore any existing script will be retained. 
if loadscript, vucreate and runtimer are used they continue to work as before apart from runtimer and waittocomplete that print messages that the command is deprecated.
As …
> Deprecate CLI runtimer

- config/oracle.xml
- images/icons.tcl
- src/db2/db2olap.tcl
- src/db2/db2oltp.tcl
- src/generic/gencli.tcl
- src/generic/gened.tcl
- src/generic/genhelp.tcl
- src/generic/gentheme.tcl
- src/generic/genvu.tcl
- src/generic/genws.tcl
- src/mariadb/mariaolap.tcl
- src/mariadb/mariaoltp.tcl
- src/mssqlserver/mssqlsolap.tcl
- src/mssqlserver/mssqlsoltp.tcl
- src/mysql/mysqlolap.tcl
- src/mysql/mysqloltp.tcl
- src/oracle/oraolap.tcl
- src/oracle/oraoltp.tcl
- src/postgresql/pgolap.tcl
- src/postgresql/pgoltp.tcl
Closes Issue #351 
Adds GUI Icon and CLI command to drop the schema created by Build Schema.
For Db2 functionality is added by running external command. To do this correctly we need to add the sqlecrea and the sqledrpd APIs to db2tcl and then we can both create and drop the schema from within HammerDB.
> Add drop schema functionality

- src/generic/gencli.tcl
Change CLI diset error message so if incorrect dictionary is given, error message reports the dictionary that the key is in or reports that the key is not in any dictionary. 
```
steve@CRANE:/opt/HammerDB-4.5$ ./hammerdbcli
HammerDB CLI v4.5
Copyright (C) 2003-2022 Steve Shaw
Type "help" for a list of commands
hammerdb>dbset db mysql
Database set to MySQL
hammerdb>diset tpcc mysql_ssl true
Dictionary "tpcc" for MySQL exists but key "mysql_ssl" doesn't, key "mysql_ssl" is in the "connection" dictionary
Type "print dict" for valid dictionaries and keys for MySQL
hammerdb>diset connection mysql_ssl true
Changed connection:mysql_ssl from false to true for MySQL
hammerdb>diset connection mysql_sst true
Dictionary "connection" for MySQL exists but key "mysql_sst" doesn't, key "mysql_sst" cannot …
```
> Improve CLI diset error message

- config/generic.xml
- src/generic/gencli.tcl
- src/generic/genws.tcl
Fixes issue #445 where keepalive time is not detected if either are zero and adds user configurable keepalive time.
Also fixes issue with vucreate automatically running loadscript if script is not already loaded.
> Fix for keepalive issue #445

- src/generic/genxml.tcl
Fixed issue #450. Error was being caused by the error message "Error creating $tablename table in $sqlitedb : $message" in src/generic/genxml.tcl. The variable $tablename does not exist inside the function "SQLiteUpdateKeyValue" and hence was throwing an exception. Changed to variable name to $table.
> Fix for issue #450

- Build/Bawt-2.1.0/Setup/HammerDB-Linux.bawt
- Build/Bawt-2.1.0/Setup/HammerDB-Windows.bawt
- agent/agent
- hammerdb
- hammerdbcli
- hammerdbcli.bat
- hammerdbws
- modules/tclreadline-1.2.tm
Adds alternative python interface to the CLI for both Linux and Windows, relying on system installed python.
Functionality will allow run scripts to be written in python as well as run interactive sessions. 
The python library will be dependent on a particular version so plan is to use v3.8 on Linux (Unbuntu 20.04), v3.6 on RHEL8 and v3.10 on Windows. However build from source can use any preferred python version instead.
Further discussion in issue #386
> Add alternative python CLI interface

- src/mariadb/mariaolap.tcl
This PR adds the logic into MariaDB's OLAP benchmark scripts to use different queries based on the engine used. Resolves #459
> Fixing queries for Columnstore issue 459

- modules/jobs-1.0.tm
- src/generic/gencli.tcl
- src/generic/genhelp.tcl
Adds a jobs joblist command that returns a list of all job ids in text. Useful for scripts querying all jobs to get a list to iterate through. Add a help message.
Fix jobs result and jobs timestamp so it reports correctly result and timestamp for all jobs. 
Update jobs format command so accepts upper and lowercase for both text and JSON
Update jobs result so it does not depend on the current set bm value but queries it for each particular job
Add geomean to jobs result for TPROC-H jobs
fix error message in case Jobid already exists
Add jobid return value for buildschema
Fix jobs timestamp was missing conversion to JSON when JSON format was selected
Add return values to python commands for jobs, vurun and buildschema https://github.com/sm-shaw/libtclpy/commit/00830c3f8da00f1cc020d78ddef4b65 …
> Updates to jobs for Docker scripts

- src/generic/gencli.tcl
Fix for Issue #472 
I have used the same clause for consistency even though timevar is not set previously in waittocomplete and is set to 0 in runtimer so the same expression will work if it does not exist or is not set to 1.
`![ info exists timevar ] || $timevar != 1`
Note the || operator is a  "short-circuiting" operator in Tcl. Meaning, they are evaluated left-to-right, and evaluation stops when the expression is known. So if the timevar variable does not exist it will not check $timevar != 1 and then fail because timevar is not set. 
This change fixes the scenario in #472 where a script that is being run fails so quickly it has already set the variable to exit the event loop before the loop has been entered, and therefore once the loop is entered it then waits forever. This would not …
> Prevent CLI hang when scripts finishes before enters event loop

- config/generic.xml
- hammerdb
- modules/emu_graph-2.0.tm
- src/generic/genmetrics.tcl
- src/generic/gentc.tcl
- src/mariadb/mariaotc.tcl
- src/mssqlserver/mssqlsotc.tcl
- src/mysql/mysqlotc.tcl
- src/oracle/oraotc.tcl
- src/postgresql/pgotc.tcl
- src/redis/redisotc.tcl
PR changes the look of the transaction counter graph and enables it to resize when the window is resized so it doesn't leave a large amount of blank space as per issue https://github.com/TPC-Council/HammerDB/issues/487
Screenshots of update in https://github.com/TPC-Council/HammerDB/issues/487
Has been tested on Windows 10/11 (incl UHD/pixelsense) and Linux Red Hat and Ubuntu.
To test requires build from source with tkpath added in https://github.com/TPC-Council/HammerDB/pull/478. Linux build needs cairo graphics which is installed by default in Ubuntu and Red Hat test installs.
Minor changes also to the CPU metrics.
> Improve Transaction counter look and feel and resize when window resized

- ChangeLog
- agent/agent
- agent/mpstat.bat
- hammerdb
- hammerdbcli
- hammerdbws
- src/generic/gened.tcl
Bump version numbers to 4.7, update copyright date to 2023 and remembering changelog update after omission for v4.6
> 4.7 versions and changelog

- src/mariadb/mariaolap.tcl
Query 15 in TPROC-H is a multi-statement query, which consists of two parts: creating the view and querying that view. Due to that it is handled using separate code then all the other queries. Currently, the execution time of query 15 is not calculated as a part of geometric mean value, which is the metric for that test.
This patch fixes that to include  query execution time in geometric mean metric. Creating/dropping the view is still not taken into that calculation, so no changes here.
Signed-off-by: Igor Konopko <igor.j.konopko@intel.com>
> Fix calculation of geomean in TPROC-H

- ChangeLog
- src/generic/geninit.tcl
- src/generic/geninitcli.tcl
- src/generic/geninitws.tcl
Closes issue #512 and enables v4.7 to start if v4.6 SQLite files already exist.
> Fix fails to delete if SQLite file open for read on Windows closes #512

- ChangeLog
- modules/jobs-1.0.tm
Fixes the issue where vu specific job timing when queried always gets printed out in text after being printed in preferred format of JSON or text.
> Fix for vu specific timing printed twice

- src/postgresql/pgoltp.tcl
An extra EXCEPTION clause was inserted at some point.  This syntax error caused the creation of the database to also miss the creation of the SLEV stored procedure when using EPAS in Oracle compatibility mode with stored procedures.
Remove the extra condition "WHEN NO_DATA_FOUND".
It appears to have be broken since before the git repository was created.
> Repair ora_compatible OSTAT procedure

- Build/Bawt-2.1.0/Setup/HammerDB-Linux.bawt
- Build/Bawt-2.1.0/Setup/HammerDB-Windows.bawt
- hammerdbcli
- modules/jobs-1.0.tm
- src/generic/genhelp.tcl
PR adds a getchart command to render job output as apache echarts/html. Intended usage is for the future modified read-only webservice to link to these charts to display job output graphically.
Also adds tickecharts package to the sourcebuild so will need to be tested by building from source to add this package to the lib directory. 
echarts are interactive so can select the values to display. 
Charts are generated on demand and stored in SQLite for future retrieval. 
Options are for:
TPROC-C result | timing | tcount
TPROC-H result | timing
Also added helper/debug function savechart to save the generated html in the interim before webservice is updated meaning this command may be removed in future but presently is useful for testing the functionality.
example usage of getchart command: …
> Add jobs getchart command

- src/generic/genvu.tcl
User and repeat delay are reversed from what is documented. So User delay is repeat delay and vice versa. This PR modifies the options to be as documented.  (By default they are both set to 500ms, so unlikely to be picked up in regualr testing). 
<html><body>
Option | Description
-- | --
User Delay(ms) | User  Delay(ms) defines the time to wait a Virtual User will wait behind the  previous Virtual User before starting its test, this is to prevent a  login storm with all Virtual Users attempting to login at the same time.
Repeat Delay(ms) | Repeat  Delay(ms) is the time that each Virtual User will wait before running  its next Iteration of the Driver Script. For the TPROC-C workload this  should be considered as an 'outer loop' to the 'inner loop' of the Total  Transactions per User in the …
> Fix User and Repeat delay reversed

- src/db2/db2opt.tcl
- src/mariadb/mariaopt.tcl
- src/mssqlserver/mssqlsopt.tcl
- src/mysql/mysqlopt.tcl
- src/oracle/oraopt.tcl
- src/postgresql/pgopt.tcl
As partly prompted by discussion in  #561 on other area adds password blanking for GUI fields.
May seem superfluous as the passwords will still be entered in the script editor in clear text, stored in the config dict and the SQLite database which is why it hasn't been done before.  
However may be of benefit when sharing screen shots of the GUI and don't want to share password field.
> Add password blank to GUI

- Docker/Dockerfile
- Docker/Readme.md
- Docker/base/Dockerfile
- Docker/maria/Dockerfile
- Docker/mssqls/Dockerfile
- Docker/mysql/Dockerfile
- Docker/oracle/Dockerfile
- Docker/postgres/Dockerfile
To reduce the duplication and minimize the image size, base/Dockerfile was created to capture the common elements of the base image.
The database specific files derive from this base image.
The top level Dockerfile uses the mssql, the more complicated image as a base, and using multistage images takes the important aspects out of oracle's image, and does the package installs for maria, mysql and postgres.
A number of changes in the base image where made:
* Apt-sources weren't used so leave them disabled.
* apt doesn't provide a stable command line interfaces, so use apt-get
* to reduce image size,  /var/lib/apt/lists/* is removed
* DEBIAN_FRONTEND=noninteractive is an environment variable rather than a build arg.
> Container file simplication

- config/mssqlserver.xml
- src/mssqlserver/mssqlsoltp.tcl
- src/mssqlserver/mssqlsopt.tcl
Added user option that enables bulk copy program (bcp) utility to speed data table insertion. This replaces the existing implementation of SQL "insert into" statements. Created additional methods for Customer, Orders and Stock tables that use bcp (bulk copy program) to load data into tables as to not interfere with existing implementation.
> Added Use bcp as a user option

- config/mssqlserver.xml
- src/mssqlserver/mssqlsoltp.tcl
- src/mssqlserver/mssqlsopt.tcl
The use_bcp option was by default set to false because bcp did not work through windows authentication. Bcp statement is now modified based on authentication type, with the -T flag used in place of a specified username and password when the connection is through windows authentication. This ensures that the bcp command will use the Windows logged in user's credentials.
> Added use_bcp default as true and enabled bcp with windows authentication

- src/generic/gencnv.tcl
Fix for Issue #590 where converting Oracle trace files does not find bind variables - test on Oracle 19c
> Skip blank lines in binds in recent Oracle trace files

- src/mssqlserver/mssqlsolap.tcl
Alter the Steps involved in creating colstore indices. Testing the current process in loading data with Colstore indices created before the data is loaded vs after the data is loaded shows a 10-20x improvement when the index is created after loading the data, when BCP is not used. When BCP is used it is more efficient to create the indices before the data is loaded.
> Alter MSSQL TPCH Colstore Index Steps

- src/mssqlserver/mssqlsoltp.tcl
Alter the TPROCC MSSQLS BCP to load the orders and customers per warehouse instead of per district. This results in a faster load time overall.
> TPROCC MSSQLS BCP Load by Warehouse

- Docker/base/Dockerfile
Updating the HammerDB version to 4.9 for Docker builds.
> Version bump to 4.9

- src/postgresql/pgmet.tcl
Resolves issue #637, discussed in #636 where error "call ash_fetch, error:can't read "public(cpucount)": no such element in array" is received accessing PostgreSQL metrics from Windows connecting to Linux.
> Fix call ash_fetch,error on Windows client running PostgreSQL metrics

- src/generic/gencli.tcl
Fixes CLI error:
`Error: can't read "threadscreated(0)": no such variable`
and replaces with message:
`Error: Cannot call vurun with Virtual Users already active`
Fix checks if threadscreated() array exists (unset by vudestroy) but thread names check is greater than 0 meaning threads remain running. If this is the case vurun returns and does not run. 
In most cases this will be because keepalive_margin is shorter than the time for a thread to finish and can be resolved by increasing keepalive_margin. 
Example with fix:
```
Vuser 1:TEST RESULT : System achieved 12527 NOPM from 29070 MariaDB TPM
Vuser 1:Gathering timing data from Active Virtual Users...
29280 MariaDB tpm
Vuser 2:FINISHED SUCCESS
Vuser 1:Calculating timings...
Vuser 1:Writing timing data to /tmp/hdbxtprofile.log
Vuser …
```
> Add check to vurun for pre-existing threads

- config/mariadb.xml
- src/mariadb/mariaoltp.tcl
- src/mariadb/mariaopt.tcl
Only compatible with MariaDB 10.7.1 and above where purge_threads are dynamic. 
Functionality is not possible to add to MySQL at the present time as innodb_purge_threads is a read only variable and functionality is dependent on setting purge_threads temporarily to a high value to accelerate the purge process. 
In the CLI the time for purge and write back with require a higher setting of keepalive_time. Plan to add a gdset command to set generic dict settings dynamically rather than only through XML to achieve this. 
Tested for both sync and async options
> Add optional purge and write back for MariaDB TPROC-C

- src/generic/gencli.tcl
- src/generic/genhelp.tcl
Add giset command to modify generic dictionary settings and print generic to print the current settings out.
Modifications are persisted to the SQLite storage. 
Update has also been made to tclpy fork to keep commands in sync https://github.com/sm-shaw/libtclpy/commit/f53b1fcda14cc15707b100178006e512b1cff928
Examples of usage of both commands as shown.
```
hammerdb>giset commandline keepalive_margin 600
Changed commandline:keepalive_margin from 10 to 600 for generic
```
```
hammerdb>print generic
Generic Dictionary Settings
theme                {
scaling        = auto
scaletheme     = auto
pixelsperpoint = auto
}
sqlitedb             {
sqlitedb_dir = TMP
}
code_highlight       {
highlight = true
}
benchmark            {
rdbms        = Oracle
bm           = TPC-C
first_result = NOPM
} …
```
> Add giset command to set generic dictionary settings

- config/mssqlserver.xml
- src/mssqlserver/mssqlsolap.tcl
- src/mssqlserver/mssqlsopt.tcl
Added a flag that allows the Order and Lineitem tables to be partitioned. Each partition spans 1 week. The parition flag is set to false by default and must be enabled.
Column Store and Row store are allowed to be partitioned.
When paritioning is enabled. Certain primary and foreign key definitions defined in HammerDB are no longer valid. HammerDB will still create those keys/constraints when the Orders and Lineitem  tables are not partitioned.`
For columnstore indices, the is an initial degredation of performance, however if the user calls Alter Index ... Reoganize or leaves the server running after the initial load for approximately 48 hours, the performance of power runs improves by 2x when compared to column store indices with no partitioning.
> MSSQLS TPCH Add Flag to Partition Orders and Lineitems

- src/mssqlserver/mssqlsolap.tcl
- src/mssqlserver/mssqlsoltp.tcl
Adds -u option to bcp based builds when running on Linux with ODBC driver 18 and trust server certificate is checked to avoid `certificate verify failed:self signed certificate` error.
Tests on Windows showed bcp used ODBC 17 so change has not been added to Windows but may need to be in future. 
Noting that the long-term solution is to extend the ODBC interface that HammerDB uses to include bcp based commands https://github.com/TPC-Council/HammerDB/issues/594 as issues such as this are a direct result of calling the external tools i.e. we have already logged in and trusted the server certificate, however using the bcp executable means we need to do this again.
> Add bcp -u option for SQL Server to trust the server certificate

- config/generic.xml
Resolves issue #667 by increasing default CLI timeout values from 10 to 60 seconds. 
Values can be increased or decreased by new giset command at the next release.
> Increase default CLI timeouts

- config/connectpool/mssqlscpool.xml
- config/mssqlserver.xml
- src/mssqlserver/mssqlsolap.tcl
- src/mssqlserver/mssqlsoltp.tcl
- src/mssqlserver/mssqlsopt.tcl
- src/mssqlserver/mssqlsotc.tcl
Adds support for Microsoft Entra authentication for SQL Server workloads as discussed in Issue https://github.com/TPC-Council/HammerDB/issues/662
Note that as discussed in the issue, I have not tested this directly and have no means to do so, so fully reliant on feedback to verify that the correct functionality has been added. Windows and SQL authentication have been re-tested to make sure the added functionality does not impact the existing ones.
One question that is worth verifying is what happens when using interactive authentication if we have multiple virtual users? We can have hundreds or thousands (with asynchronous connections) - will all virtual users produce an interactive prompt? 
To test, it is recommended to build from source on windows. This is very easy and just takes 1 …
> Add support for Microsoft Entra authentication for SQL Server

- config/mysql.xml
- scripts/tcl/oceanbase/tproch/ob_tproch.sh
- scripts/tcl/oceanbase/tproch/ob_tproch_buildschema.tcl
- scripts/tcl/oceanbase/tproch/ob_tproch_deleteschema.tcl
- scripts/tcl/oceanbase/tproch/ob_tproch_result.tcl
- scripts/tcl/oceanbase/tproch/ob_tproch_run.tcl
- src/mysql/mysqlolap.tcl
- src/mysql/mysqlopt.tcl
- src/mysql/mysqlotc.tcl
As described in https://github.com/TPC-Council/HammerDB/issues/563. This PR support Oceanbase TPROC-H  by adding a compatible parameter. 
Co-authored-by: XiTang <xi.tang@intel.com>
TPROC-H
#Check 1 Database Exist
#Check 2 Tables Exist
#Check 3 supplier count in schema is the same as dict setting
#Check 4 Tables are indexed
#Check 5 Tables are populated
#Consistency check
> Add Support for oceanbase tpch

- src/db2/db2opt.tcl
- src/mariadb/mariaopt.tcl
- src/mssqlserver/mssqlsopt.tcl
- src/mysql/mysqlopt.tcl
- src/oracle/oraopt.tcl
- src/postgresql/pgopt.tcl
As we've added options over time, some of the GUI options dialog boxes have become too large. 
This PR takes the typical tabbed properties dialog approach to break the dialog into 2 tabs of connections and settings to reduce the size. 
Example from Linux with MySQL
New Connection
New Settings
Current Dialog
> Change GUI properties dailogs to tabbed

- src/postgresql/pgoltp.tcl
Resolves Issue #681 by modifying lines that are deleted so that final close-brace remains when XML connect pool option is selected. 
Note that as mentioned in the issue PostgreSQL stored procedures are not supported with prepared statements and therefore this option will always default to functions and will error if trying to use stored procedures.
> Fix missing close-brace in PostgreSQL XML Connect Pool option

- src/postgresql/pgoltp.tcl
Fix for consistency check 2 fails in PostgreSQL because all values are out by 1 e.g.
```
Vuser 1:resArray(0,d_id) = 1
Vuser 1:resArray(0,d_w_id) = 6
Vuser 1:resArray(0,order_max) = 22816
Vuser 1:resArray(0,order_next) = 22815
Vuser 1:resArray(1,d_id) = 1
Vuser 1:resArray(1,d_w_id) = 7
Vuser 1:resArray(1,order_max) = 22892
Vuser 1:resArray(1,order_next) = 22891
Vuser 1:resArray(10,d_id) = 6
Vuser 1:resArray(10,d_w_id) = 6
Vuser 1:resArray(10,order_max) = 22637
Vuser 1:resArray(10,order_next) = 22636
...
```
> Fix RETURNING d_next_o_id in NEWORD

- modules/jobs-1.0.tm
- src/db2/db2oltp.tcl
- src/mariadb/mariaoltp.tcl
- src/mssqlserver/mssqlsoltp.tcl
- src/mysql/mysqloltp.tcl
- src/oracle/oraoltp.tcl
- src/postgresql/pgoltp.tcl
Pull request adds a database version number query to the TPROC-C timed test and prints the string such as `DBVersion:16.0.1000.6` at the start of the test. If the version cannot be queried or the version is not an expected version of digits and dots then the test will not error but instead record the version as `DBVersion:NULL`
This can then be queried at a later point with the jobs db command. 
```
hammerdb>job 6601BCF63E8403E263532363 db
[
"MSSQLServer",
"16.0.1000.6"
]
```
The enhancement means we will now have a record of the database version stored along with the test data.
> Add Database version to TPROC-C timed test

- src/generic/gencli.tcl
- src/generic/gened.tcl
Automatically update the VU generic settings inside the `vuset` command (CLI) and inside the Virtual User Options (GUI) to make it easier to persist VU settings across restarts. Write the values to SQLite storage when set or the user presses OK.
Example of the new vuset (CLI) behavior across the restarts:
```
$ ./hammerdbcli
HammerDB CLI v4.10
Copyright (C) 2003-2024 Steve Shaw
Type "help" for a list of commands
Initialized Jobs on-disk database /tmp/hammer.DB using existing tables (335,872 KB)
hammerdb>vurun
Script loaded, Type "print script" to view
Vuser 1 created MONITOR - WAIT IDLE
Vuser 2 created - WAIT IDLE
Vuser 3 created - WAIT IDLE
Vuser 4 created - WAIT IDLE
Vuser 5 created - WAIT IDLE
5 Virtual Users Created with Monitor VU
...
hammerdb>print generic
Generic Dictionary …
```
> Persist VU settings across restarts

- src/generic/gentpcc.tcl
PR Closes #715 by moving output messaging for use all warehouses option to one message for all assigned warehouses, rather than one per warehouse. Previously when printing one line per assigned warehouse can lead to a bottleneck with Jobs enabled to record all the output in SQLite when there are 1000s of warehouses allocated.
> Consolidate output for use all warehouses option

- modules/xtprof-1.0.tm
Fixed typo in variable name `xtto` causing incorrect timeout assignment in xtprof module.
> Bug Fix, wrong timeout value assignment in xtprof module.

- src/generic/gencli.tcl
- src/generic/gened.tcl
For TPROC-C in both GUI & CLI PR temporary disables the output to SQLite when a test workload script is selected and re-enables it if a timed workload is selected. Prevents filling the SQLite database with large amounts of data when running a test workload.
> Disable SQLite output for TPROC-C test workloads

- src/mssqlserver/mssqlsolap.tcl
- src/mssqlserver/mssqlsoltp.tcl
As discussed in https://github.com/TPC-Council/HammerDB/issues/594 using the bcp executable for bulk loads provides excellent performance, however we need to provide login details for bcp that results in extending the function for different connection options. for example on Linux only ODBC driver 18 can trust the server certificate with -u option. 
It would be better if we could use bcp under the existing connection. https://github.com/TPC-Council/HammerDB/issues/594 suggests extending the tdbc::odbc interface to include the bcp_init, bcp_exec commands etc, however bulk insert https://learn.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-ver16 looks like it already allows us to do this. 
This PR replaces calling the bcp executable with a bulk insert …
> Replace bcp executable with bulk insert for SQL Server builds

- src/mssqlserver/mssqlsolap.tcl
Adds following indexes for partitioned row store. o_orderkey_ind specifically benefits the old sales refresh function. 
```
alter table dbo.orders add constraint orders_pk primary key (o_orderdate,o_orderkey) with (fillfactor = 95, maxdop=$maxdop)
create clustered index o_orderkey_ind on orders(o_orderkey) with (fillfactor=95, sort_in_tempdb=on, maxdop=$maxdop)
```
> Add indexes to orders table for SQL TPROC-H partitioned row store

- src/mssqlserver/mssqlsolap.tcl
When loading the MSSQL TPCH load with a single user the myposition variable is not defined. When load_orders is called with that argument the error "Error in Virtual User 1: Error: can't read "myposition": no such variable" is thrown.
Added a line when threaded is 'Single Threaded' to set myposition to 1.
> MSSQL TPCH Load does not work for Single User

- images/icons.tcl
- modules/emu_graph-2.0.tm
- modules/tkcon-2.7.10.tm
- src/generic/gened.tcl
- src/generic/genmetrics.tcl
- src/generic/genmodes.tcl
- src/generic/gentab.tcl
- src/generic/gentc.tcl
- src/generic/gentheme.tcl
- src/generic/genvu.tcl
- src/oracle/oramet.tcl
- src/postgresql/pgmet.tcl
As discussed in https://github.com/TPC-Council/HammerDB/issues/751 PR adds awbreezedark theme option to both Windows and Linux. PR restores the dark theme option lost when moving to SVG graphics, however new dark theme also now uses SVG graphics so continues to scale on UHD displays for both light and dark options (tested on Surface Book display). 
For testing option can be selected by changing the scaletheme option in genericxml to awbreezedark.
```
<?xml version="1.0" encoding="utf-8"?>
<hammerdb>
<theme>
<scaling>auto</scaling>
<scaletheme>awbreezedark</scaletheme>
<pixelsperpoint>auto</pixelsperpoint>
</theme>
...
```
> Add awbreezedark theme option to GUI

- modules/xtprof-1.0.tm
PR unsets dicts and thread shared variables used to gather timing data for the xtprof time profiler after each run and the timing data has been reported. There is also a check to see if the thread shared variables exist at the start of a run which remains. 
Virtual user independent profiler array is already unset after use.
> Free thread shared variables after xtprof run

- src/generic/gencli.tcl
- src/generic/gened.tcl
- src/generic/genvu.tcl
As detailed in #791 a virtual user can report permission denied on Windows when loading a database library. 
This occurs when the virtual user thread attempts to open the library while it is still being created as Windows can only open libraries from a file system. 
Issue does not occur on Linux. 
Fix implements retry logic when loading a database library and if permission denied is received will clear up and retry the load.
Testing also showed that on occasions the package require failed but the package commands exist so test also checks if command exists and does the same clean up and retry. 
Tests show that with delay values of 0, libraries now load. 
PR also fixes mismatch of delay values introduced by https://github.com/TPC-Council/HammerDB/commit/5ff2f8aa0c98af733b4281308a4163e6cfee1 …
> Fix permission denied on loading database libraries on Windows

- modules/tclreadline-1.2.1.tm
Adds catch to stty command for terminal reset so error not received if command cannot be found and/or is not needed when running from external script.
> Add catch to CLI stty command on Linux

- src/mariadb/mariaoltp.tcl
Testing shows no performance difference with innodb_snapshot_isolation set to 1 or 0 for TPROC-C workload and therefore we can turn it off at the session level to prevent errors being reported when it is set at the global level to 1.
> Add handling of innodb_snapshot_isolation to MariaDB

- hammerdbws
- modules/jobs-1.0.tm
- modules/wapp-1.1.tm
- src/generic/genws.tcl
Pull request enable HammerDB web service to run as SCGI application tested under Nginx.
```
/etc/nginx/sites-available$ cat hammerdb
server {
listen 8081;
server_name _;
location / {
include scgi_params;
scgi_pass 127.0.0.1:8080;
proxy_hide_header Content-Security-Policy;  # Handle CSP with HammerDB
proxy_set_header Accept-Encoding "";
sub_filter_types text/html text/css application/javascript;
sub_filter_once off;
sub_filter 'http://' 'https://';
}
}
/etc/nginx/sites-enabled$ ls -l
hammerdb -> /etc/nginx/sites-available/hammerdb
$ sudo nginx -t
$ sudo nginx -s reload
```
Run HammerDB web service with scgi argument
```
./hammerdbws scgi
HammerDB Web Service v5.0
Copyright © HammerDB Ltd hosted by tpc.org 2019-2025
Type "help" for a list of commands
Starting HammerDB Web Service on port …
```
> Enable Web Service to run as SCGI application
